server:
  port: 8090
spring:
  data:
    mongodb:
      username: ${DB_USER}
      password: ${DB_PASSWORD}
      host: localhost
      port: 27017
      database: customer
      authentication-database: admin