spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/item
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
      format_sql: true
      default_schema: item
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    baseline-on-migrate: true
    enabled: true
    baseline-description: "init"
    baseline-version: 0
    user: postgres
    password: ${DB_PASSWORD}
server:
  port: 8050